In [ ]:
import numpy as np

array : 넘파이 배열 생성 

In [ ]:
# 문제 1
# 파이썬 리스트 scores = [85, 90, 78, 92, 88]를 넘파이 배열로 변환하여 출력하세요
arr_scores = np.array([85, 90, 78, 92, 88])
print(arr_scores)

# 문제 2
# 리스트 heights = [160, 165, 170, 175, 180] 를 넘파이 배열로 변환하여 출력하세요
arr_heights = np.array([160, 165, 170, 175, 180])
print(arr_heights)

# 문제 3
# 리스트 prices = [1200, 1500, 1800, 2100] 넘파이 배열로 변환하여 출력하세요
arr_prices = np.array([1200, 1500, 1800, 2100])
print(arr_prices)

# 문제 4
# 리스트 temps = [20, 22, 19, 25, 30] 넘파이 배열로 변환하여 출력하세요
arr_temps = np.array([20, 22, 19, 25, 30])
print(arr_temps)

arange : 지정한 범위로 넘파이 배열 생성 

In [ ]:
# 문제 1
# 0부터 4까지 숫자를 원소로 가지는 배열을 생성하세요.
arr1 = np.arange(5)
print("문제1:", arr1)

# 문제 2
# 0부터 9까지 숫자를 원소로 가지는 배열을 생성하세요.
arr2 = np.arange(10)
print("문제2:", arr2)

# 문제 3
# 3부터 7까지 숫자를 원소로 가지는 배열을 생성하세요.
arr3 = np.arange(3, 8)
print("문제3:", arr3)

# 문제 4
# -2부터 2까지 숫자를 원소로 가지는 배열을 생성하세요.
arr4 = np.arange(-2, 3)
print("문제4:", arr4)

# 문제 5
# 100부터 104까지 숫자를 원소로 가지는 배열을 생성하세요.
arr5 = np.arange(100, 105)
print("문제5:", arr5)

1차원 배열 인덱스

In [ ]:
# 1번
arr = np.array([10, 20, 30, 40, 50])

# 배열의 첫 번째 값을 꺼내서 출력하세요.
# 결과: 10
print(arr[0])

# 배열의 세 번째 값을 꺼내서 출력하세요.
# 결과: 30
print(arr[2])

# 배열의 마지막 값을 꺼내서 출력하세요.
# 결과: 50
print(arr[-1])

# 배열의 두 번째 값을 200으로 바꾸세요.
# 결과: [ 10 200  30  40  50]
arr[1] = 200
print(arr)

# 배열의 네 번째 값을 999로 바꾸세요.
# 결과: [  10  200   30  999   50]
arr[3] = 999
print(arr)

In [ ]:
# 2번
arr = np.array(["가", "나", "다", "라", "마"])

# 배열의 두 번째 값을 꺼내서 출력하세요.
# 결과: 나
print(arr[1])

# 배열의 네 번째 값을 꺼내서 출력하세요.
# 결과: 라
print(arr[3])

# 배열의 마지막 값을 꺼내서 출력하세요.
# 결과: 마
print(arr[-1])

# 배열의 첫 번째 값을 '하'로 바꾸세요.
# 결과: ['하' '나' '다' '라' '마']
arr[0] = "하"
print(arr)

# 배열의 세 번째 값을 '호'로 바꾸세요.
# 결과: ['하' '나' '호' '라' '마']
arr[2] = "호"
print(arr)

1차원 배열 슬라이스

In [ ]:
# 1번
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# 배열의 처음 3개 값을 꺼내서 출력하세요.
# 결과: [10 20 30]
print(arr[0:3])

# 배열의 네 번째부터 끝까지 값을 꺼내서 출력하세요.
# 결과: [40 50 60 70]
print(arr[3:])

# 배열의 두 번째부터 다섯 번째까지 값을 꺼내서 출력하세요.
# 결과: [20 30 40 50]
print(arr[1:5])

In [ ]:
# 2번
arr = np.array(["a", "b", "c", "d", "e", "f", "g"])

# 배열의 처음 3개 값을 꺼내서 출력하세요.
# 결과: ['a' 'b' 'c']
print(arr[0:3])

# 배열의 네 번째부터 끝까지 값을 꺼내서 출력하세요.
# 결과: ['d' 'e' 'f' 'g']
print(arr[3:])

# 배열의 두 번째부터 다섯 번째까지 값을 꺼내서 출력하세요.
# 결과: ['b' 'c' 'd' 'e']
print(arr[1:5])

2차원 배열 인덱싱

In [ ]:
# 1번
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# 첫 번째 행의 두 번째 값을 꺼내서 출력하세요.
# 결과: 20
print("문제1:", arr[0, 1])

# 세 번째 행의 첫 번째 값을 꺼내서 출력하세요.
# 결과: 70
print("문제2:", arr[2, 0])

# 두 번째 행 전체를 꺼내서 출력하세요.
# 결과: [40 50 60]
print("문제3:", arr[1, :])

# 두 번째 열 전체를 꺼내서 출력하세요.
# 결과: [20 50 80]
print("문제4:", arr[:, 1])

# 첫 번째 행의 세 번째 값을 300으로 바꾸세요.
# 결과:
# [[ 10  20 300]
#  [ 40  50  60]
#  [ 70  80  90]]
arr[0, 2] = 300
print(arr)

# 세 번째 행의 두 번째 값을 999로 바꾸세요.
# 결과:
# [[ 10  20 300]
#  [ 40  50  60]
#  [ 70 999  90]]
arr[2, 1] = 999
print(arr)

In [ ]:
# 2번
arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])

# 두 번째 행의 세 번째 값을 꺼내서 출력하세요. 결과: 7
print("문제1:", arr[1, 2])

# 네 번째 행의 첫 번째 값을 꺼내서 출력하세요. 결과: 13
print("문제2:", arr[3, 0])

# 세 번째 행 전체를 꺼내서 출력하세요. 결과: [ 9 10 11 12]
print("문제3:", arr[2, :])

# 네 번째 열 전체를 꺼내서 출력하세요. 결과: [ 4  8 12 16]
print("문제4:", arr[:, 3])

# 첫 번째 행의 네 번째 값을 100으로 바꾸세요.
# [[  1   2   3 100] 
# ..
arr[0, 3] = 100
print(arr)

2차원 배열 슬라이스

In [ ]:
# 문제 1

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
 
# 첫 번째 행의 앞 2개 숫자를 꺼내서 출력하세요. 결과: [10 20]
arr[0, 0:2]

# 두 번째 행부터 세 번째 행까지 전체를 꺼내서 출력하세요.
# 결과:
# [[40 50 60]
#  [70 80 90]]
arr[1:3, :]

# 모든 행에서 두 번째와 세 번째 열만 꺼내서 출력하세요.
# 결과:
# [[20 30]
#  [50 60]
#  [80 90]]
arr[:, 1:3]

# 첫 번째 행과 두 번째 행에서 첫 번째 열만 꺼내서 출력하세요.
# 결과: [10 40]
arr[0:2, 0]

# 첫 번째 행부터 세 번째 행까지, 두 번째 열만 꺼내서 출력하세요.
# 결과: [20 50 80]
arr[:, 1]

불리언 인덱스

In [ ]:
# 1번
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# 배열에서 30보다 큰 값만 꺼내서 출력하세요. 
# 결과: [40 50 60 70]
print("문제1:", arr[arr > 30])

# 배열에서 짝수 값만 꺼내서 출력하세요.
# 결과: [10 20 30 40 50 60 70]
print("문제2:", arr[arr % 2 == 0])

# 배열에서 50보다 큰 값을 모두 999로 바꾸세요.
# 결과: [ 10  20  30  40  50 999 999]
arr[arr > 50] = 999
print("문제3:", arr)

In [ ]:
# 직원 이름 배열
employees = np.array(["짱구", "철수", "유리", "맹구", "훈이"])

# 직원별 월급 (만원 단위)
salaries = np.array([250, 320, 280, 400, 150])

# '맹구'의 급여를 조회하세요.
salaries[employees == "맹구"]

# 급여가 300만원 이상인 직원들의 이름을 출력하세요
employees[salaries >= 300]

# 급여가 200만원 미만인 직원들의 급여를 모두 200으로 올리세요.
salaries[salaries < 200] = 200
salaries

reshape : 배열의 형태 바꾸기

In [ ]:
# 문제 1

# 0부터 11까지 숫자를 생성한 뒤, 3행 4열 배열로 바꾸세요.
# 결과:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
arr1 = np.arange(12).reshape(3, 4)
arr1

# 1부터 16까지 숫자를 생성한 뒤, 4행 4열 배열로 바꾸세요.
# 결과:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]
#  [13 14 15 16]]
arr2 = np.arange(1, 17).reshape(4, 4)
arr2

# 1부터 20까지 숫자를 생성한 뒤, 5행 4열 배열로 바꾸세요.
# 결과:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]
#  [13 14 15 16]
#  [17 18 19 20]]
arr3 = np.arange(1, 21).reshape(5, 4)
arr3

# 10부터 25까지 숫자를 생성한 뒤, 4행 4열 배열로 바꾸세요.
# 결과:
# [[10 11 12 13]
#  [14 15 16 17]
#  [18 19 20 21]
#  [22 23 24 25]]
arr4 = np.arange(10, 26).reshape(4, 4)
arr4

랜덤값

In [ ]:
# 표준정규분포에서 랜덤값 5개를 생성하세요.
arr1 = np.random.standard_normal(5)
arr1

# 균일분포에서 랜덤값 5개를 생성하세요.
arr2 = np.random.uniform(size=5)
arr2

조건문

In [ ]:
# 문제 1

# 배열 [5, 12, 7, 20, 3] 에서
# 10보다 크면 그대로 두고, 10 이하면 0으로 바꾸세요.
# 결과: [ 0 12  0 20  0]
arr = np.array([5, 12, 7, 20, 3])
result1 = np.where(arr > 10, 100, 0)
print("문제1:", result1)

# 배열 [15, 8, 22, 6, 13] 에서
# 짝수면 1, 홀수면 -1로 바꾸세요.
# 결과: [-1  1  1  1 -1]
arr = np.array([15, 8, 22, 6, 13])
result2 = np.where(arr % 2 == 0, 1, -1)
print("문제2:", result2)

# 배열 [10, 20, 30, 40, 50] 과 [1, 2, 3, 4, 5]을 만들고
# 조건 배열 [True, False, True, False, True] 를 사용해
# 조건이 True일 때는 첫 번째 배열 값, False일 때는 두 번째 배열 값을 선택하세요.
# 결과: [10  2 30  4 50]
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])
cond = np.array([True, False, True, False, True])
result3 = np.where(cond, arr1, arr2)
print("문제3:", result3)

# 배열 [-5, -2, 0, 3, 7] 에서
# 0보다 크면 100, 아니면 -100으로 바꾸세요.
# 결과: [-100 -100 -100  100  100]
arr = np.array([-5, -2, 0, 3, 7])
result4 = np.where(arr > 0, 100, -100)
print("문제4:", result4)

최대,최소,합계,평균 구하기  
21~22p

In [ ]:
food_kcal = np.array([250, 550, 400, 800])

# 1. 총합
total = food_kcal.sum()

# 2. 평균
avg = food_kcal.mean()

# 3. 최고 칼로리
high = food_kcal.max()

# 4. 최저 칼로리
low = food_kcal.min()

print("총합:", total)
print("평균:", avg)
print("최고 칼로리:", high)
print("최저 칼로리:", low)

In [ ]:
# 일주일 동안 운동한 시간(분)
exercise_time = np.array([30, 45, 60, 20, 40, 50, 35])

total = exercise_time.sum()
avg = exercise_time.mean()
high = exercise_time.max()
low = exercise_time.min()

print("총 운동 시간:", total, "분")
print("평균 운동 시간:", avg, "분")
print("가장 오래 한 운동:", high, "분")
print("가장 짧게 한 운동:", low, "분")